# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rootsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('date_parution', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/portrait')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('date_mort', models.DateField(null=True)),
                ('description', models.TextField()),
                ('faits', models.TextField()),
                ('fonctions', models.TextField()),
                ('nbrFavoris', models.IntegerField(default=0)),
                ('nbrCommentaire', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=rootsapp.models.get_image_path)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('pseudo', models.CharField(max_length=30)),
                ('mail_adresse', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('commentaire', models.TextField()),
                ('pseudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rootsapp.Personne')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favoris',
            field=models.ManyToManyField(to='rootsapp.Personne'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personne',
            name='oeuvres',
            field=models.ManyToManyField(to='rootsapp.Oeuvre'),
        ),
    ]
